### PR TITLE
Add has_plugin method to PluginManager

### PR DESCRIPTION
**Pull request by nicoddemus**
Related to pytest-dev/pytest#932

### CODE REVIEW

**Comment by hpk42** [comment]
is this PR still to be merged now that PytestPluginManager has it itself?

**Comment by RonnyPfannschmidt** [comment]
would be nice if py.test could "loose" it

**Comment by nicoddemus** [comment]
I think it makes sense for pluggy to have a `has_plugin` method. Unfortunately Pytest still needs to have `hasplugin` for compatibility reasons. 

After this is merged, we would change Pytest's `hasplugin` just a proxy for Pluggy's `has_plugin`.

**Comment by RonnyPfannschmidt** [comment]
:+1:

**Comment by nicoddemus** [comment]
Rebased to resolve conflicts

**Pull request merged**
